### ISSUE TITLE
more cautious reducers

### ISSUE THREAD

**Issue by zachlite** [FriteGames/zombie-shoppers#2]
> the classic combineReducers function makes it so that each subreducer can _only_ modify its own state. but since you let them return { zombies: zState }, the zombies could technicall modify the placer by doing something like { zombies: zState, player: pState }

**Comment by zachlite** [comment]
@samouri, can you show me an example of a classic combineReducers function?

**Comment by samouri** [comment]
https://redux.js.org/docs/api/combineReducers.html

**Comment by samouri** [comment]
The core of the redux version is actually very little logic.  It’s got a bunch of edge case handling just to make DevEx better.  Worth checking out. 

https://github.com/reactjs/redux/blob/master/src/combineReducers.js
